name: My Website
url: https://wolong6336.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# Base pathname for links.
base: ''

# Navigation bar links.
navigation:
  - title: Home
    link: /
